USE matrimonial_db;

INSERT INTO cms_pages (slug, title, content, status)
VALUES
('home-showcase', 'Homepage showcase profiles', '[{"id":"showcase-1","name":"Mira Shah","age":27,"city":"Ahmedabad","community":"Gujarati","profession":"Architect","photo":"https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=900&q=85","cover":"https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1200&q=85"},{"id":"showcase-2","name":"Naina Kapoor","age":26,"city":"Delhi","community":"Punjabi","profession":"Doctor","photo":"https://images.unsplash.com/photo-1524503033411-c9566986fc8f?auto=format&fit=crop&w=900&q=85","cover":"https://images.unsplash.com/photo-1523438885200-e635ba2c371e?auto=format&fit=crop&w=1200&q=85"},{"id":"showcase-3","name":"Riya Iyer","age":28,"city":"Bengaluru","community":"Tamil","profession":"Software Engineer","photo":"https://images.unsplash.com/photo-1512316609839-ce289d3eba0a?auto=format&fit=crop&w=900&q=85","cover":"https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=1200&q=85"},{"id":"showcase-4","name":"Sana Khan","age":29,"city":"Hyderabad","community":"Sunni","profession":"Entrepreneur","photo":"https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=85","cover":"https://images.unsplash.com/photo-1505932794465-147d1f1b2c97?auto=format&fit=crop&w=1200&q=85"},{"id":"showcase-5","name":"Avni Rao","age":25,"city":"Pune","community":"Marathi","profession":"Interior Stylist","photo":"https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&w=900&q=85","cover":"https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=85"},{"id":"showcase-6","name":"Kavya Menon","age":28,"city":"Chennai","community":"Malayali","profession":"Finance Analyst","photo":"https://images.unsplash.com/photo-1534751516642-a1af1ef26a56?auto=format&fit=crop&w=900&q=85","cover":"https://images.unsplash.com/photo-1545232979-8bf68ee9b1af?auto=format&fit=crop&w=1200&q=85"}]', 'published'),
('marriage-moments', 'Marriage moments', '[{"title":"Sacred Ceremony","text":"Traditional vows, family blessings, and graceful wedding rituals.","image":"https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=1200&q=88"},{"title":"Floral Mandap","text":"Soft pink florals and elegant wedding decor for a dream celebration.","image":"https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1200&q=88"},{"title":"Wedding Rings","text":"A timeless symbol of commitment, trust, and togetherness.","image":"https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1200&q=88"},{"title":"Bride & Groom","text":"Beautiful beginnings made with compatibility and family confidence.","image":"https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=88"}]', 'published'),
('quick-search-filters', 'Quick search filters', '["Mumbai","Delhi","Bengaluru","Doctor","Engineer","Verified only"]', 'published'),
('journey-cards', 'Homepage journey cards', '[{"title":"Create your profile","icon":"user","text":"Add personal, family, lifestyle, education, and partner preference details."},{"title":"Verify your identity","icon":"badge","text":"Build trust with mobile, email, profile photo, and optional document verification."},{"title":"Discover compatible matches","icon":"search","text":"Use filters and compatibility highlights to find serious profiles."},{"title":"Connect with confidence","icon":"heart","text":"Send interests, shortlist profiles, chat after acceptance, and schedule meetings."}]', 'published'),
('trust-cards', 'Homepage trust cards', '[{"title":"Privacy-first profiles","icon":"lock","text":"Control photo visibility, contact access, and private profile mode."},{"title":"Family-friendly matching","icon":"users","text":"Families can review matches and coordinate conversations."},{"title":"Admin reviewed safety","icon":"shield","text":"Verification, reporting, moderation, and suspicious account checks."}]', 'published'),
('wedding-services', 'Wedding services', '["Wedding planners","Venue booking","Photography","Makeup artists","Decorators","Invitation cards"]', 'published'),
('feature-cards', 'Homepage feature cards', '[{"title":"Verified profiles","icon":"shield","text":"Admin approval, identity checks, and visible profile status."},{"title":"Smart discovery","icon":"sliders","text":"Filter by city, community, education, profession, and age."},{"title":"Private conversations","icon":"message","text":"Send interest first, then start meaningful conversations."}]', 'published')
ON DUPLICATE KEY UPDATE title = VALUES(title), content = VALUES(content), status = VALUES(status);
