USE matrimonial_db;

INSERT INTO users (role, name, email, password_hash, age, height, city, religion, community, profession, education, income, bio, photo, status, verified, premium)
VALUES
('admin', 'Admin', 'admin@matrimony.local', 'e86f78a8a3caf0b60d8e74e5942aa6d86dc150cd3c03338aef25b7d2d7e3acc7', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'approved', 1, 0),
('user', 'Aarav Mehta', 'user@example.com', '3e7c19576488862816f13b512cacf3e4ba97dd97243ea0bd6a2ad1642d86ba72', 29, '5ft 10in', 'Mumbai', 'Hindu', 'Gujarati', 'Product Manager', 'MBA', '18 LPA', 'Warm, practical, family-oriented, and always planning the next hill-station weekend.', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=80', 'approved', 1, 1),
('user', 'Mira Shah', 'mira@example.com', '3e7c19576488862816f13b512cacf3e4ba97dd97243ea0bd6a2ad1642d86ba72', 27, '5ft 5in', 'Ahmedabad', 'Hindu', 'Gujarati', 'Architect', 'M.Arch', '14 LPA', 'Design-led thinker, loves old cities, quiet cafes, and close-knit family rituals.', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80', 'approved', 1, 1),
('user', 'Naina Kapoor', 'naina@example.com', '3e7c19576488862816f13b512cacf3e4ba97dd97243ea0bd6a2ad1642d86ba72', 26, '5ft 4in', 'Delhi', 'Hindu', 'Punjabi', 'Doctor', 'MBBS', '16 LPA', 'Grounded, curious, and happiest around books, music, and meaningful conversations.', 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=900&q=80', 'approved', 1, 0),
('user', 'Riya Iyer', 'riya@example.com', '3e7c19576488862816f13b512cacf3e4ba97dd97243ea0bd6a2ad1642d86ba72', 28, '5ft 6in', 'Bengaluru', 'Hindu', 'Tamil', 'Software Engineer', 'B.Tech', '22 LPA', 'Tech lead by day, classical dancer by evening, weekend brunch loyalist.', 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80', 'pending', 0, 1)
ON DUPLICATE KEY UPDATE email = VALUES(email);

INSERT INTO subscription_plans (code, name, price, duration_days, features)
VALUES
('free', 'Free', 0, 0, JSON_ARRAY('Limited profile views', 'Limited interests/day', 'Basic search')),
('premium', 'Premium', 1499, 30, JSON_ARRAY('Unlimited messaging', 'Advanced filters', 'Profile visitors', 'Priority listing')),
('elite', 'Elite Family', 4999, 90, JSON_ARRAY('Family account', 'Relationship assistant', 'Profile boost', 'Verification concierge'))
ON DUPLICATE KEY UPDATE name = VALUES(name), price = VALUES(price), features = VALUES(features);

INSERT INTO cms_pages (slug, title, content, status)
VALUES
('home-banner', 'Bharat Matrimony', 'Discover graceful, verified profiles in a beautiful matchmaking experience designed for families, meaningful conversations, and confident life decisions.', 'published'),
('about-us', 'About Bharat Matrimony', 'A premium matrimonial platform built for verified, family-friendly, privacy-first matchmaking.', 'published'),
('success-stories', 'Real journeys, meaningful beginnings', 'Mira & Aarav | Ahmedabad to Mumbai | Their families connected through a verified interest and scheduled two family calls before meeting.\nRiya & Karan | Bengaluru | Smart compatibility helped them discover shared values around career, culture, and family life.\nNaina & Dev | Delhi | A premium profile boost helped both families find each other during an active search week.', 'published'),
('blog', 'Matrimony Blog', 'Relationship guidance, wedding planning, profile tips, and family conversation advice.', 'published'),
('faq', 'Frequently Asked Questions', 'Find answers about registration, verification, privacy, subscriptions, and profile safety.', 'published'),
('help-center', 'Help Center', 'Get support for account access, profile updates, reporting, verification, and subscription questions.', 'published'),
('terms-and-conditions', 'Terms and Conditions', 'Use Bharat Matrimony respectfully, honestly, and only for genuine marriage-focused connections.', 'published'),
('privacy-policy', 'Privacy Policy', 'We protect user privacy through profile controls, secure sessions, and careful access to personal details.', 'published'),
('safety-center', 'Verification, moderation, and fraud protection', 'Government ID, PAN, employment, income, selfie, face match, content moderation, scam reporting, and emergency support workflows are represented here.', 'published'),
('seo-pages', 'SEO Pages', 'City, community, religion, and profession landing pages can be managed here for search visibility.', 'draft'),
('home-showcase', 'Homepage showcase profiles', '[{"id":"showcase-1","name":"Mira Shah","age":27,"city":"Ahmedabad","community":"Gujarati","profession":"Architect","photo":"https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=900&q=85","cover":"https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1200&q=85"},{"id":"showcase-2","name":"Naina Kapoor","age":26,"city":"Delhi","community":"Punjabi","profession":"Doctor","photo":"https://images.unsplash.com/photo-1524503033411-c9566986fc8f?auto=format&fit=crop&w=900&q=85","cover":"https://images.unsplash.com/photo-1523438885200-e635ba2c371e?auto=format&fit=crop&w=1200&q=85"},{"id":"showcase-3","name":"Riya Iyer","age":28,"city":"Bengaluru","community":"Tamil","profession":"Software Engineer","photo":"https://images.unsplash.com/photo-1512316609839-ce289d3eba0a?auto=format&fit=crop&w=900&q=85","cover":"https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=1200&q=85"},{"id":"showcase-4","name":"Sana Khan","age":29,"city":"Hyderabad","community":"Sunni","profession":"Entrepreneur","photo":"https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=85","cover":"https://images.unsplash.com/photo-1505932794465-147d1f1b2c97?auto=format&fit=crop&w=1200&q=85"},{"id":"showcase-5","name":"Avni Rao","age":25,"city":"Pune","community":"Marathi","profession":"Interior Stylist","photo":"https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&w=900&q=85","cover":"https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=85"},{"id":"showcase-6","name":"Kavya Menon","age":28,"city":"Chennai","community":"Malayali","profession":"Finance Analyst","photo":"https://images.unsplash.com/photo-1534751516642-a1af1ef26a56?auto=format&fit=crop&w=900&q=85","cover":"https://images.unsplash.com/photo-1545232979-8bf68ee9b1af?auto=format&fit=crop&w=1200&q=85"}]', 'published'),
('marriage-moments', 'Marriage moments', '[{"title":"Sacred Ceremony","text":"Traditional vows, family blessings, and graceful wedding rituals.","image":"https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=1200&q=88"},{"title":"Floral Mandap","text":"Soft pink florals and elegant wedding decor for a dream celebration.","image":"https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1200&q=88"},{"title":"Wedding Rings","text":"A timeless symbol of commitment, trust, and togetherness.","image":"https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1200&q=88"},{"title":"Bride & Groom","text":"Beautiful beginnings made with compatibility and family confidence.","image":"https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=88"}]', 'published'),
('quick-search-filters', 'Quick search filters', '["Mumbai","Delhi","Bengaluru","Doctor","Engineer","Verified only"]', 'published'),
('journey-cards', 'Homepage journey cards', '[{"title":"Create your profile","icon":"user","text":"Add personal, family, lifestyle, education, and partner preference details."},{"title":"Verify your identity","icon":"badge","text":"Build trust with mobile, email, profile photo, and optional document verification."},{"title":"Discover compatible matches","icon":"search","text":"Use filters and compatibility highlights to find serious profiles."},{"title":"Connect with confidence","icon":"heart","text":"Send interests, shortlist profiles, chat after acceptance, and schedule meetings."}]', 'published'),
('trust-cards', 'Homepage trust cards', '[{"title":"Privacy-first profiles","icon":"lock","text":"Control photo visibility, contact access, and private profile mode."},{"title":"Family-friendly matching","icon":"users","text":"Families can review matches and coordinate conversations."},{"title":"Admin reviewed safety","icon":"shield","text":"Verification, reporting, moderation, and suspicious account checks."}]', 'published'),
('wedding-services', 'Wedding services', '["Wedding planners","Venue booking","Photography","Makeup artists","Decorators","Invitation cards"]', 'published'),
('feature-cards', 'Homepage feature cards', '[{"title":"Verified profiles","icon":"shield","text":"Admin approval, identity checks, and visible profile status."},{"title":"Smart discovery","icon":"sliders","text":"Filter by city, community, education, profession, and age."},{"title":"Private conversations","icon":"message","text":"Send interest first, then start meaningful conversations."}]', 'published')
ON DUPLICATE KEY UPDATE title = VALUES(title), content = VALUES(content), status = VALUES(status);
